[package]
name = "collint"
version = "0.2.3"
edition = "2021"

[dependencies]
rand = "0.8.5"
bimap = "0.6.3"
config = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
indicatif = "0.17.3"
itertools = "0.10.5"
rayon = "1.7"