# ---- allowed values -----
# + choose one to select M
#   - group_range = { start = integer, end = integer }
#   - group_sizes = [ integer, .. ]
# + choose one to select B
#   - blackboard_range = { start = integer, end = integer }
#   - blackboard_sizes = [ integer, .. ]
# + chooses how many time each (m,b) pair are repeated
#   - n_repeat = integer > 0
# + choose csv file to write to format is (m, b, t) or (m, b, t, c)
#   - output = "path/to/file.csv"
# + choose if to compute the cost and include in csv as the last column
#   - compute_cost = true | false
# + choose number of threads to use when computing (you can crash your computer if you make this too big)
#   - n_threads = integer > 0
# + if blackboard algorithm runs N times, the file will be flushed to disk every (N / flush_frequency) times. (higher = more frequent backups, slower; lower = less frequent updates, faster)
#   - flush_frequency = integer >= 0

group_range = { start = 1, end = 2 }
blackboard_range = { start = 1, end = 2 }
n_repeat = 3
output = "default.csv"
compute_cost = true
n_threads = 10
flush_frequency = 10