#================================================      README     ====================================================#
#                                                                                                                     #
# Copy this file for each experiment to run. Recommend to change output parameter to match name of this file.         # 
# Optional parameters do not need to be included.                                                                     # 
# For best performance turn on threads, and set flush_frequeny pretty high, ~100 is okay.                             #
#                                                                                                                     #
#------------------------------------------------  allowed values ----------------------------------------------------#
#                                                                                                                     #
# + choose one to select M                                                                                            #
#   - group_range = { start = integer, end = integer }                                                                #
#   - group_sizes = [ integer, .. ]                                                                                   #
#                                                                                                                     #
# + choose one to select B                                                                                            #
#   - blackboard_range = { start = integer, end = integer }                                                           #
#   - blackboard_sizes = [ integer, .. ]                                                                              #
#                                                                                                                     #
# + chooses how many time each (m,b) pair are repeated                                                                #
#   - n_repeat = integer > 0                                                                                          #
#                                                                                                                     #
# + choose csv file to write to format is (m, b, t, c) or (m, b, t)                                                   #
#   - output = "path/to/file.csv"                                                                                     #
#                                                                                                                     #
# + [optional] choose if to compute the cost and include in csv as the last column                                    #
#   [default(true)]                                                                                                   #
#   - compute_cost = true | false                                                                                     #
#                                                                                                                     #
# + [optional] choose number of threads to use when computing (you can crash your computer if you make this too big)  #
#   [default(true)]                                                                                                   #
#   - use_threads = true | false                                                                                      #
#                                                                                                                     #
# + [optional] write results to disk every flush_frequency results.                                                   #
#   - flush_frequency = integer >= 0                                                                                  #
#   [default(100)]                                                                                                    #
#                                                                                                                     #
#=====================================================================================================================#


# Required Parameters
group_range = { start = 1, end = 7 }
blackboard_sizes = [1, 2, 3, 4, 5, 6, 7]
n_repeat = 10
output = "default.csv"

# Optional Parameters
compute_cost = true
use_threads = true
flush_frequency = 100